chore: send the w3c log to the Actions console

diff --git a/.github/workflows/rss-build.yml b/.github/workflows/rss-build.yml
--- a/.github/workflows/rss-build.yml
+++ b/.github/workflows/rss-build.yml
@@ -30,7 +30,12 @@ jobs:
       
       - name: Log RSS validation output
         run: |
-            curl -s -F "url=https://raw.githubusercontent.com/charliefox84/iryna-watch/dev/rss.xml" https://validator.w3.org/feed/check.cgi > ./rss-validator.log  
+            curl -s -F "url=https://raw.githubusercontent.com/charliefox84/iryna-watch/dev/rss.xml" https://validator.w3.org/feed/check.cgi > ./rss-validator.log
+      
+      - name: Show validator output
+        run: |
+          echo "Validator output:"
+          cat rss-validator.log || echo "Log not found"  
 
       - name: Push changes
         if: github.ref == 'refs/heads/dev'
